# Generated by Django 2.0.4 on 2019-01-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.TextField(db_index=True)),
                ('image', models.SlugField(max_length=220)),
                ('yyt', models.SlugField(max_length=220)),
                ('rarity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Card', unique_for_date='timestamp')),
            ],
        ),
    ]
