# Generated by Django 2.0.4 on 2019-01-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
