# Generated by Django 2.1.5 on 2019-02-01 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20190118_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Card'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('card', 'timestamp')},
        ),
    ]
