# Generated by Django 2.2.2 on 2019-06-14 09:55

from django.db import migrations, models
import django.db.models.deletion


def export_timeSP(apps, schema_editor):
    """
    """

    Price = apps.get_model("card", "Price")
    TimeSP = apps.get_model("card", "TimeSP")

    objs = []

    times = {}
    for t in Price.objects.values_list("timestamp", flat=True).distinct():
        times[str(t)] = TimeSP.objects.create(value=t)

    for p in Price.objects.iterator():
        p._timestamp = times[str(p.timestamp)]
        objs.append(p)

    for k, v in times.items():
        Price.objects.filter(timestamp=k).update(_timestamp=v)


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20190201_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='_timestamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.TimeSP', null=True),
        ),
        migrations.RunPython(export_timeSP),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={},
        ),
        migrations.RemoveField(
            model_name='price',
            name='timestamp',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='_timestamp',
            new_name='timestamp',
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('card', 'timestamp')},
        ),
    ]
